version: '3'
services:
  web:
      build: .
      ports:
       - "8080:8080"
      links:
       - db
      environment:
        REDIS_URL: db:6379
  db:
      image: redis
      ports:
       - "6379:6379"
